title_template: 'Round {}'
main_event_id:
comment:
rounds:
  - title: 'Flex'
    comment:
    groups:
      - first_time: '08:00'
        last_time: '16:00'
        interval: '00:15'
      - first_time: '18:45'
        last_time: '22:00'
        interval: '00:15'
    max_players_in_group: 5

  - title: Joint Start
    start_time: '17:00'
    comment:
    registration:
      end_time: '16:30'
